repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.12 # we specify the same version as in uv.lock, but can be different
  hooks:
    # Run the linter.
    - id: ruff-check
      types_or: [ python, pyi ]
      args: [ --fix]
      pass_filenames: false
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]
      pass_filenames: false

- repo: local
  hooks:
    - id: ty-check
      name: ty check
      entry: uv run ty check src tests
      language: system
      types_or: [python, pyi]
      exclude: ^notebooks/
      pass_filenames: false
      
- repo: https://github.com/kynan/nbstripout
  rev: 0.7.1
  hooks:
      - id: nbstripout
