services:
  app-stream-data:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "entrypoints/app_stream_data.py"]
    volumes:
      - ./data:/app/data
      - ./conf:/app/conf
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  mlflow_server:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - mlflow
      - server
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --backend-store-uri
      - sqlite:////app/mlflow/mlflow.db
      - --default-artifact-root
      - file:///app/mlflow/artifacts
      - --serve-artifacts
      - --allowed-hosts
      - "*"
      - --cors-allowed-origins
      - "*"
    ports:
      - "8080:8080"
    volumes:
      - mlflow_data:/app/mlflow
      - ./data:/app/data
      - ./conf:/app/conf

  app-ml-train:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "entrypoints/training.py"]
    volumes:
      - mlflow_data:/app/mlflow
      - ./data:/app/data
      - ./conf:/app/conf
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:8080
    depends_on:
      - mlflow_server
      - app-stream-data

  app-ml-inference:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "entrypoints/inference_real_time.py"]
    restart: unless-stopped
    volumes:
      - mlflow_data:/app/mlflow
      - ./data:/app/data
      - ./conf:/app/conf
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:8080
    depends_on:
      app-ml-train:
        condition: service_completed_successfully

  app-ui:
    build:
      context: .                    # Build context is the project root
      dockerfile: Dockerfile        # Use the shared Dockerfile
    command: ["python", "entrypoints/app_ui.py"]  # Run the Dash UI app
    restart: unless-stopped
    ports:
      - "8050:8050"                 # Expose port 8050 for web access
    volumes:
      - mlflow_data:/app/mlflow
      - ./data:/app/data
      - ./conf:/app/conf
    environment:
      - KEDRO_ENV=local
      - MLFLOW_TRACKING_URI=http://mlflow_server:8080
      - MLFLOW_UI_URI=${MLFLOW_UI_URI:-http://localhost:8080}
      - DEBUG=False
      - KEDRO_VIZ_URI=${KEDRO_VIZ_URI:-http://localhost:4141}
    depends_on:
      - mlflow_server
      - app-stream-data

  kedro-viz:
    build:
      context: .                    # Build context is the project root
      dockerfile: Dockerfile        # Use the shared Dockerfile
    command: ["kedro", "viz", "run", "--host", "0.0.0.0", "--port", "4141", "--no-browser"]
    ports:
      - "4141:4141"                 # Expose port 4141 for Kedro Viz UI
    depends_on:
        app-ml-train:
          condition: service_completed_successfully
      
volumes:
  mlflow_data: